name: BetterLobby
version: @version@
main: de.jalumu.betterlobby.BetterLobby
author: JanLuca
commands:
  build:
    permission: lobby.build
  setSpawn:
    permission: lobby.setspawn

softdepend: [PlaceholderAPI,CloudNetAPI]