name: BetterLobby
version: @version@
main: de.jalumu.betterlobby.BetterLobby
author: JanLuca
commands:
  build:
    permission: lobby.build
  setSpawn:
    permission: lobby.setspawn
  spawn:
    permission: lobby.spawn
  push:
    permission: lobby.push

softdepend: [PlaceholderAPI,CloudNetAPI]