name: BetterLobby
version: Dev
main: de.jalumu.betterlobby.BetterLobby
author: JanLuca
commands:
  betterlobby:
    description: Shows plugin infos
  build:
    permission: lobby.build
  setSpawn:
    permission: lobby.setspawn
  spawn:
    permission: lobby.spawn
  push:
    permission: lobby.push
  fly:
    permission: lobby.fly
  heal:
    permission: lobby.heal
  deathmatch:
    permission: lobby.deathmatch

softdepend: [PlaceholderAPI, HolographicDisplays, CloudNetAPI]